### ISSUE TITLE
14일차 문제(20190213)

### ISSUE THREAD

**Issue by ckh80** [hrkim28/TCT#15]
- 문제

정수 X에 사용할 수 있는 연산은 다음과 같이 세 가지 이다.
  1. X가 3으로 나누어 떨어지면, 3으로 나눈다.
  2. X가 2로 나누어 떨어지면, 2로 나눈다.
  3. 1을 뺀다.

정수 N이 주어졌을 때, 위와 같은 연산 세 개를 적절히 사용해서 1을 만들려고 한다.
연산을 사용하는 횟수의 최소값을 출력하시오.

- 입력
첫째 줄에 1보다 크거나 같고, 1000000보다 작거나 같은 정수 N이 주어진다.

- 출력
첫째 줄에 연산을 하는 횟수의 최솟값을 출력한다.

[입력1]
10
[출력1]
3

[입력2]
30
[출력2]
4

[힌트]
10의 경우 10 -> 9 -> 3 -> 1			: 3번
30의 경우 30 -> 10 -> 9 -> 3 -> 1	        : 4번

**Comment by Kimsiwon75** [comment]
우선 출석

**Comment by ximpley** [comment]
세가지 연산 중에 가장 빠르게 줄어드는 3의 배수를 만드는 빠른 방법을 찾으면 되겠네요. 좋은 문제입니다.

**Comment by ckh80** [comment]
다음 출제차는 원영미 책임님 이십니다. 감사합니다. ^^

**Comment by junwc** [comment]
출첵합니다. 금일 파이썬 리뷰어는 임영찬 책임입니다.

**Comment by youngmi-won** [comment]
출첵합니다~

**Comment by ahryunPark** [comment]
출석합니다.

**Comment by yelgit** [comment]
출첵 합니다.

**Comment by hrkim28** [comment]
출석합니다

**Comment by spica07** [comment]
출석합니다.

**Comment by tjdah13** [comment]
출석 합니다.

**Comment by cnsjunwoolee** [comment]
파일 올리는데 에러 났어요

$ git push
To https://github.com/hrkim28/TCT.git
 ! [rejected]        master -> master (fetch first)
error: failed to push some refs to 'https://github.com/hrkim28/TCT.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details.

**Comment by hrkim28** [comment]
> 파일 올리는데 에러 났어요
> 
> $ git push
> To https://github.com/hrkim28/TCT.git
> ! [rejected] master -> master (fetch first)
> error: failed to push some refs to 'https://github.com/hrkim28/TCT.git'
> hint: Updates were rejected because the remote contains work that you do
> hint: not have locally. This is usually caused by another repository pushing
> hint: to the same ref. You may want to first integrate the remote changes
> hint: (e.g., 'git pull ...') before pushing again.
> hint: See the 'Note about fast-forwards' in 'git push --help' for details.

@cnsjunwoolee  git pull 먼저 수행하신 후에, 다시 push 해보세요

**Comment by kimkkhee** [comment]
출석함당~

**Comment by choiswon** [comment]
출석합니다.

**Comment by hseo-lee** [comment]
저도 출석합니당.

**Comment by khbanhub** [comment]
출석합니다.

**Comment by hjkimsky** [comment]
우선 출석입니다. 회의끝나고 고민해야겠어요.

**Comment by cherrylime** [comment]
출석합니다.. 일 다끝나고 해볼께요..

**Comment by clamp83** [comment]
출석합니다 .
